[package]
name = "merkle_cli"
version = "0.1.0"
authors = ["ErisedKT <sanyaverma0303@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

merkletree = "0.21.0"
ring = "0.16.15"